package com.vinhnh.calculator.uitls;

import com.vinhnh.calculator.models.CurrencyModel;

import java.util.ArrayList;

public class CurrencyUtils {
    public static ArrayList<CurrencyModel> getCurrency()  {
        ArrayList<CurrencyModel> currencyList = new ArrayList<>();
        currencyList.add(new CurrencyModel("United Arab Emirates", "UAE Dirham", "AED"));
        currencyList.add(new CurrencyModel("Afghanistan", "Afghan Afghani", "AFN"));
        currencyList.add(new CurrencyModel("Albania", "Albanian Lek", "ALL"));
        currencyList.add(new CurrencyModel("Armenia", "Armenian Dram", "AMD"));
        currencyList.add(new CurrencyModel("Netherlands Antilles", "Netherlands Antillian Guilder", "ANG"));
        currencyList.add(new CurrencyModel("Angola", "Angolan Kwanza", "AOA"));
        currencyList.add(new CurrencyModel("Argentina", "Argentine Peso", "ARS"));
        currencyList.add(new CurrencyModel("Australia", "Australian Dollar", "AUD"));
        currencyList.add(new CurrencyModel("Aruba", "Aruban Florin", "AWG"));
        currencyList.add(new CurrencyModel("Azerbaijan", "Azerbaijani Manat", "AZN"));
        currencyList.add(new CurrencyModel("Bosnia and Herzegovina", "Bosnia and Herzegovina Mark", "BAM"));
        currencyList.add(new CurrencyModel("Barbados", "Barbados Dollar", "BBD"));
        currencyList.add(new CurrencyModel("Bangladesh", "Bangladeshi Taka", "BDT"));
        currencyList.add(new CurrencyModel("Bulgaria", "Bulgarian Lev", "BGN"));
        currencyList.add(new CurrencyModel("Bahrain", "Bahraini Dinar", "BHD"));
        currencyList.add(new CurrencyModel("Burundi", "Burundian Franc", "BIF"));
        currencyList.add(new CurrencyModel("Bermuda", "Bermudian Dollar", "BMD"));
        currencyList.add(new CurrencyModel("Brunei", "Brunei Dollar", "BND"));
        currencyList.add(new CurrencyModel("Bolivia", "Bolivian Boliviano", "BOB"));
        currencyList.add(new CurrencyModel("Brazil", "Brazilian Real", "BRL"));
        currencyList.add(new CurrencyModel("Bahamas", "Bahamian Dollar", "BSD"));
        currencyList.add(new CurrencyModel("Bhutan", "Bhutanese Ngultrum", "BTN"));
        currencyList.add(new CurrencyModel("Botswana", "Botswana Pula", "BWP"));
        currencyList.add(new CurrencyModel("Belarus", "Belarusian Ruble", "BYN"));
        currencyList.add(new CurrencyModel("Belize", "Belize Dollar", "BZD"));
        currencyList.add(new CurrencyModel("Canada", "Canadian Dollar", "CAD"));
        currencyList.add(new CurrencyModel("Democratic Republic of the Congo", "Congolese Franc", "CDF"));
        currencyList.add(new CurrencyModel("Switzerland", "Swiss Franc", "CHF"));
        currencyList.add(new CurrencyModel("Chile", "Chilean Peso", "CLP"));
        currencyList.add(new CurrencyModel("China", "Chinese Renminbi", "CNY"));
        currencyList.add(new CurrencyModel("Colombia", "Colombian Peso", "COP"));
        currencyList.add(new CurrencyModel("Costa Rica", "Costa Rican Colon", "CRC"));
        currencyList.add(new CurrencyModel("Cuba", "Cuban Peso", "CUP"));
        currencyList.add(new CurrencyModel("Cape Verde", "Cape Verdean Escudo", "CVE"));
        currencyList.add(new CurrencyModel("Czech Republic", "Czech Koruna", "CZK"));
        currencyList.add(new CurrencyModel("Djibouti", "Djiboutian Franc", "DJF"));
        currencyList.add(new CurrencyModel("Denmark", "Danish Krone", "DKK"));
        currencyList.add(new CurrencyModel("Dominican Republic", "Dominican Peso", "DOP"));
        currencyList.add(new CurrencyModel("Algeria", "Algerian Dinar", "DZD"));
        currencyList.add(new CurrencyModel("Egypt", "Egyptian Pound", "EGP"));
        currencyList.add(new CurrencyModel("Eritrea", "Eritrean Nakfa", "ERN"));
        currencyList.add(new CurrencyModel("Ethiopia", "Ethiopian Birr", "ETB"));
        currencyList.add(new CurrencyModel("European Union", "Euro", "EUR"));
        currencyList.add(new CurrencyModel("Fiji", "Fiji Dollar", "FJD"));
        currencyList.add(new CurrencyModel("Falkland Islands", "Falkland Islands Pound", "FKP"));
        currencyList.add(new CurrencyModel("Faroe Islands", "Faroese Króna", "FOK"));
        currencyList.add(new CurrencyModel("United Kingdom", "Pound Sterling", "GBP"));
        currencyList.add(new CurrencyModel("Georgia", "Georgian Lari", "GEL"));
        currencyList.add(new CurrencyModel("Guernsey", "Guernsey Pound", "GGP"));
        currencyList.add(new CurrencyModel("Ghana", "Ghanaian Cedi", "GHS"));
        currencyList.add(new CurrencyModel("Gibraltar", "Gibraltar Pound", "GIP"));
        currencyList.add(new CurrencyModel("The Gambia", "Gambian Dalasi", "GMD"));
        currencyList.add(new CurrencyModel("Guinea", "Guinean Franc", "GNF"));
        currencyList.add(new CurrencyModel("Guatemala", "Guatemalan Quetzal", "GTQ"));
        currencyList.add(new CurrencyModel("Guyana", "Guyanese Dollar", "GYD"));
        currencyList.add(new CurrencyModel("Hong Kong", "Hong Kong Dollar", "HKD"));
        currencyList.add(new CurrencyModel("Honduras", "Honduran Lempira", "HNL"));
        currencyList.add(new CurrencyModel("Croatia", "Croatian Kuna", "HRK"));
        currencyList.add(new CurrencyModel("Haiti", "Haitian Gourde", "HTG"));
        currencyList.add(new CurrencyModel("Hungary", "Hungarian Forint", "HUF"));
        currencyList.add(new CurrencyModel("Indonesia", "Indonesian Rupiah", "IDR"));
        currencyList.add(new CurrencyModel("Israel", "Israeli New Shekel", "ILS"));
        currencyList.add(new CurrencyModel("Isle of Man", "Manx Pound", "IMP"));
        currencyList.add(new CurrencyModel("India", "Indian Rupee", "INR"));
        currencyList.add(new CurrencyModel("Iraq", "Iraqi Dinar", "IQD"));
        currencyList.add(new CurrencyModel("Iran", "Iranian Rial", "IRR"));
        currencyList.add(new CurrencyModel("Iceland", "Icelandic Króna", "ISK"));
        currencyList.add(new CurrencyModel("Jersey", "Jersey Pound", "JEP"));
        currencyList.add(new CurrencyModel("Jamaica", "Jamaican Dollar", "JMD"));
        currencyList.add(new CurrencyModel("Jordan", "Jordanian Dinar", "JOD"));
        currencyList.add(new CurrencyModel("Japan", "Japanese Yen", "JPY"));
        currencyList.add(new CurrencyModel("Kenya", "Kenyan Shilling", "KES"));
        currencyList.add(new CurrencyModel("Kyrgyzstan", "Kyrgyzstani Som", "KGS"));
        currencyList.add(new CurrencyModel("Cambodia", "Cambodian Riel", "KHR"));
        currencyList.add(new CurrencyModel("Kiribati", "Kiribati Dollar", "KID"));
        currencyList.add(new CurrencyModel("Comoros", "Comorian Franc", "KMF"));
        currencyList.add(new CurrencyModel("South Korea", "South Korean Won", "KRW"));
        currencyList.add(new CurrencyModel("Kuwait", "Kuwaiti Dinar", "KWD"));
        currencyList.add(new CurrencyModel("Cayman Islands", "Cayman Islands Dollar", "KYD"));
        currencyList.add(new CurrencyModel("Kazakhstan", "Kazakhstani Tenge", "KZT"));
        currencyList.add(new CurrencyModel("Laos", "Lao Kip", "LAK"));
        currencyList.add(new CurrencyModel("Lebanon", "Lebanese Pound", "LBP"));
        currencyList.add(new CurrencyModel("Sri Lanka", "Sri Lanka Rupee", "LKR"));
        currencyList.add(new CurrencyModel("Liberia", "Liberian Dollar", "LRD"));
        currencyList.add(new CurrencyModel("Lesotho", "Lesotho Loti", "LSL"));
        currencyList.add(new CurrencyModel("Libya", "Libyan Dinar", "LYD"));
        currencyList.add(new CurrencyModel("Morocco", "Moroccan Dirham", "MAD"));
        currencyList.add(new CurrencyModel("Moldova", "Moldovan Leu", "MDL"));
        currencyList.add(new CurrencyModel("Madagascar", "Malagasy Ariary", "MGA"));
        currencyList.add(new CurrencyModel("North Macedonia", "Macedonian Denar", "MKD"));
        currencyList.add(new CurrencyModel("Myanmar", "Burmese Kyat", "MMK"));
        currencyList.add(new CurrencyModel("Mongolia", "Mongolian Tögrög", "MNT"));
        currencyList.add(new CurrencyModel("Macau", "Macanese Pataca", "MOP"));
        currencyList.add(new CurrencyModel("Mauritania", "Mauritanian Ouguiya", "MRU"));
        currencyList.add(new CurrencyModel("Mauritius", "Mauritian Rupee", "MUR"));
        currencyList.add(new CurrencyModel("Maldives", "Maldivian Rufiyaa", "MVR"));
        currencyList.add(new CurrencyModel("Malawi", "Malawian Kwacha", "MWK"));
        currencyList.add(new CurrencyModel("Mexico", "Mexican Peso", "MXN"));
        currencyList.add(new CurrencyModel("Malaysia", "Malaysian Ringgit", "MYR"));
        currencyList.add(new CurrencyModel("Mozambique", "Mozambican Metical", "MZN"));
        currencyList.add(new CurrencyModel("Namibia", "Namibian Dollar", "NAD"));
        currencyList.add(new CurrencyModel("Nigeria", "Nigerian Naira", "NGN"));
        currencyList.add(new CurrencyModel("Nicaragua", "Nicaraguan Córdoba", "NIO"));
        currencyList.add(new CurrencyModel("Norway", "Norwegian Krone", "NOK"));
        currencyList.add(new CurrencyModel("Nepal", "Nepalese Rupee", "NPR"));
        currencyList.add(new CurrencyModel("New Zealand", "New Zealand Dollar", "NZD"));
        currencyList.add(new CurrencyModel("Oman", "Omani Rial", "OMR"));
        currencyList.add(new CurrencyModel("Panama", "Panamanian Balboa", "PAB"));
        currencyList.add(new CurrencyModel("Peru", "Peruvian Sol", "PEN"));
        currencyList.add(new CurrencyModel("Papua New Guinea", "Papua New Guinean Kina", "PGK"));
        currencyList.add(new CurrencyModel("Philippines", "Philippine Peso", "PHP"));
        currencyList.add(new CurrencyModel("Pakistan", "Pakistani Rupee", "PKR"));
        currencyList.add(new CurrencyModel("Poland", "Polish Złoty", "PLN"));
        currencyList.add(new CurrencyModel("Paraguay", "Paraguayan Guaraní", "PYG"));
        currencyList.add(new CurrencyModel("Qatar", "Qatari Riyal", "QAR"));
        currencyList.add(new CurrencyModel("Romania", "Romanian Leu", "RON"));
        currencyList.add(new CurrencyModel("Serbia", "Serbian Dinar", "RSD"));
        currencyList.add(new CurrencyModel("Russia", "Russian Ruble", "RUB"));
        currencyList.add(new CurrencyModel("Rwanda", "Rwandan Franc", "RWF"));
        currencyList.add(new CurrencyModel("Saudi Arabia", "Saudi Riyal", "SAR"));
        currencyList.add(new CurrencyModel("Solomon Islands", "Solomon Islands Dollar", "SBD"));
        currencyList.add(new CurrencyModel("Seychelles", "Seychellois Rupee", "SCR"));
        currencyList.add(new CurrencyModel("Sudan", "Sudanese Pound", "SDG"));
        currencyList.add(new CurrencyModel("Sweden", "Swedish Krona", "SEK"));
        currencyList.add(new CurrencyModel("Singapore", "Singapore Dollar", "SGD"));
        currencyList.add(new CurrencyModel("Saint Helena", "Saint Helena Pound", "SHP"));
        currencyList.add(new CurrencyModel("Sierra Leone", "Sierra Leonean Leone", "SLL"));
        currencyList.add(new CurrencyModel("Somalia", "Somali Shilling", "SOS"));
        currencyList.add(new CurrencyModel("Suriname", "Surinamese Dollar", "SRD"));
        currencyList.add(new CurrencyModel("South Sudan", "South Sudanese Pound", "SSP"));
        currencyList.add(new CurrencyModel("São Tomé and Príncipe", "São Tomé and Príncipe Dobra", "STN"));
        currencyList.add(new CurrencyModel("Syria", "Syrian Pound", "SYP"));
        currencyList.add(new CurrencyModel("Eswatini", "Eswatini Lilangeni", "SZL"));
        currencyList.add(new CurrencyModel("Thailand", "Thai Baht", "THB"));
        currencyList.add(new CurrencyModel("Tajikistan", "Tajikistani Somoni", "TJS"));
        currencyList.add(new CurrencyModel("Turkmenistan", "Turkmenistan Manat", "TMT"));
        currencyList.add(new CurrencyModel("Tunisia", "Tunisian Dinar", "TND"));
        currencyList.add(new CurrencyModel("Tonga", "Tongan Paʻanga", "TOP"));
        currencyList.add(new CurrencyModel("Turkey", "Turkish Lira", "TRY"));
        currencyList.add(new CurrencyModel("Trinidad and Tobago", "Trinidad and Tobago Dollar", "TTD"));
        currencyList.add(new CurrencyModel("Tuvalu", "Tuvaluan Dollar", "TVD"));
        currencyList.add(new CurrencyModel("Taiwan", "New Taiwan Dollar", "TWD"));
        currencyList.add(new CurrencyModel("Tanzania", "Tanzanian Shilling", "TZS"));
        currencyList.add(new CurrencyModel("Ukraine", "Ukrainian Hryvnia", "UAH"));
        currencyList.add(new CurrencyModel("Uganda", "Ugandan Shilling", "UGX"));
        currencyList.add(new CurrencyModel("United States", "United States Dollar", "USD"));
        currencyList.add(new CurrencyModel("Uruguay", "Uruguayan Peso", "UYU"));
        currencyList.add(new CurrencyModel("Uzbekistan", "Uzbekistani So'm", "UZS"));
        currencyList.add(new CurrencyModel("Venezuela", "Venezuelan Bolívar Soberano", "VES"));
        currencyList.add(new CurrencyModel("Vietnam", "Vietnamese Đồng", "VND"));
        currencyList.add(new CurrencyModel("Vanuatu", "Vanuatu Vatu", "VUV"));
        currencyList.add(new CurrencyModel("Samoa", "Samoan Tālā", "WST"));
        currencyList.add(new CurrencyModel("CEMAC", "Central African CFA Franc", "XAF"));
        currencyList.add(new CurrencyModel("Organisation of Eastern Caribbean States", "East Caribbean Dollar", "XCD"));
        currencyList.add(new CurrencyModel("International Monetary Fund", "Special Drawing Rights", "XDR"));
        currencyList.add(new CurrencyModel("CFA", "West African CFA franc", "XOF"));
        currencyList.add(new CurrencyModel("Collectivités d'Outre-Mer", "CFP Franc", "XPF"));
        currencyList.add(new CurrencyModel("Yemen", "Yemeni Rial", "YER"));
        currencyList.add(new CurrencyModel("South Africa", "South African Rand", "ZAR"));
        currencyList.add(new CurrencyModel("Zambia", "Zambian Kwacha", "ZMW"));
        currencyList.add(new CurrencyModel("Zimbabwe", "Zimbabwean Dollar", "ZWL"));
        return currencyList;
    }
}
